apiVersion: v1
kind: Service
metadata:
  name: resumeai-service
spec:
  selector:
    app: resumeai
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 443
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer
